name: "Build"
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix develop -c zola build
    - run: find public -type f
    - if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: blog
        path: |
          public
    - if: startsWith(github.ref, 'refs/tags/')
      run: |
        pushd public
        tar czf ../blog.tar.gz *
        popd
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        make_latest: 'true'
        files: |
          blog.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
