name: "Test"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix develop -c zola build
    - run: find public -type f
    - if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: blog
        path: |
          public
